### ISSUE TITLE
3.0.1 crashes warhammer3

### ISSUE THREAD

**Issue by kartebi** [Frodo45127/rpfm#193]
Changing stuff in data.pack with 3.0.1 release, warhammer3 crashes on start. With 2.6.6 everything was working fine.
Downloaded 2.6.6 again, no schema found... so i cant make any changes

**Comment by mextrinc** [comment]
+1, opening the modified.log inside %appdata%

"data.pack size mismatch"

**Comment by ahamm3rs** [comment]
same here

**Comment by zli929** [comment]
Same. Can't even edit scripts anymore for supply lines and realm cooldown.

**Comment by derpinsk** [comment]
@ahamm3rs @mextrinc @kartebi @zli929
Dont edit main data.pack, create new .pack file.

I used this old tutorial https://www.youtube.com/watch?v=MrQovjozTLY and everything works fine.

**Comment by 63413** [comment]
@derpinsk 

How can you enable the .pack file when, mod manager isn't released yet?

Thanks in advance.

**Comment by Frodo45127** [comment]
Fixed in the next build. If you have a packfile that doesn't load, just open it with 3.0.2 (when it's built) or open it with 3.0.1 and change its type to anything else, then back to what it had before.

**Comment by derpinsk** [comment]
@63413 
To enable custom .pack file mods you can use [this](http://www.twcenter.net/forums/showthread.php?623840-Using-the-quot-User-Script-txt-quot-File) guide, and if it still doesnt load you can 
 create "mods" folder in  
- #### C:\Users\\(username)\AppData\Roaming\The Creative Assembly\Warhammer3\GDK\ 

and put your .pack file there

**Comment by mextrinc** [comment]
> @63413 To enable custom .pack file mods you can use [this](http://www.twcenter.net/forums/showthread.php?623840-Using-the-quot-User-Script-txt-quot-File) guide, and if it still doesnt load you can create "mods" folder in
> 
> * #### C:\Users\(username)\AppData\Roaming\The Creative Assembly\Warhammer3\GDK\
> 
> and put your .pack file there

Thank you for trying to help but I still can't get it to work... haha. I'll just wait for 3.0.2

**Comment by 63413** [comment]
> > @63413 To enable custom .pack file mods you can use [this](http://www.twcenter.net/forums/showthread.php?623840-Using-the-quot-User-Script-txt-quot-File) guide, and if it still doesnt load you can create "mods" folder in
> > 
> > * #### C:\Users(username)\AppData\Roaming\The Creative Assembly\Warhammer3\GDK\
> > 
> > and put your .pack file there
> 
> Thank you for trying to help but I still can't get it to work... haha. I'll just wait for 3.0.2

Change user.script.txt to read only and make sure to change your .pack file type to "mod".

**Comment by Frodo45127** [comment]
Properly fixed this time. The previous fix I tried to push broke more things......

**Comment by mextrinc** [comment]
> 

Wait so, from example: mod1.pack to mod1.mod?

**Comment by mextrinc** [comment]
> > > @63413 To enable custom .pack file mods you can use [this](http://www.twcenter.net/forums/showthread.php?623840-Using-the-quot-User-Script-txt-quot-File) guide, and if it still doesnt load you can create "mods" folder in
> > > 
> > > * #### C:\Users(username)\AppData\Roaming\The Creative Assembly\Warhammer3\GDK\
> > > 
> > > and put your .pack file there
> > 
> > 
> > Thank you for trying to help but I still can't get it to work... haha. I'll just wait for 3.0.2
> 
> Change user.script.txt to read only and make sure to change your .pack file type to "mod".

Wait so, from example: mod1.pack to mod1.mod?

**Comment by mextrinc** [comment]
> Properly fixed this time. The previous fix I tried to push broke more things......

Great, there will be a 3.0.2 release right? :D

**Comment by Frodo45127** [comment]
Released already... lets hope it doesn't break more. Anyway, as this is fixed, closing the issue. If you have a broken mod, open it with the new version and switch its packfile type back and forward to another type. It should fix the packfile.
